### ISSUE TITLE
Creating a new risk throws Fatal Error

### ISSUE THREAD

**Issue by cleary** [DeBortoliWines/dotProject#1]
Hi @mattbell87,
Testing the risk module today - and got the following error:

`EAR category: | Fatal error: Call to a member function _() on a non-object in /data/srv/debortoli.private/dotproject_dbw_git/modules/risks/controlling/risks_controlling.php on line 31
`

![image](https://user-images.githubusercontent.com/2577966/36764280-fd4f8778-1c7f-11e8-9b76-d4f616a55ffb.png)

Steps to reproduce: 
1. Create a new Project (but no tasks yet)
2. Add a New Risk to the Project
3. Attach the risk to all tasks

**Comment by mattbell87** [comment]
@cleary fixed in 826cecb900da731ceb14f5f55c72db1b09bc288e
