### ISSUE TITLE
Image not displaying

### ISSUE THREAD

**Issue by ShaneDunn** [DeBortoliWines/dotProject#11]
when viewing a task, the following image is not found and displayed
http://dotproject.debortoli.private/images/dbw/sign_explain.png

**Comment by cleary** [comment]
I can't replicate this -

Can you give us an example url + screenshot of where this occurs?

![image](https://user-images.githubusercontent.com/2577966/60142128-d7865000-97fb-11e9-8272-697f010b1d07.png)

**Comment by ShaneDunn** [comment]
Example

![image](https://user-images.githubusercontent.com/1137105/60142682-42d12180-97fe-11e9-951f-c4516bab519d.png)

**Comment by cleary** [comment]
Sorted, we'd provided a bunch of custom fields and icons which I didn't pull across in the standard dotproject checkout... I'm actually keener to use less custom stuff, but I've brought them all in regardless for now
