### ISSUE TITLE
FrappeGantt: My Gantt is showing more tasks than I own

### ISSUE THREAD

**Issue by cleary** [DeBortoliWines/dotProject#14]
I own 4x tasks:

![image](https://user-images.githubusercontent.com/2577966/60243488-b3119d00-98fb-11e9-8e87-ef2bd70ffab9.png)

My Gantt should show any of the 4x tasks that are active for this month (so, 4 or less), but:
![image](https://user-images.githubusercontent.com/2577966/60243559-d9373d00-98fb-11e9-8044-34a1e285289e.png)

**Comment by Givo29** [comment]
After some quick testing I've found that this only occurs for users that have tasks in the `My Tasks` tab. For users without any tasks in the first tab the gantt chart shows no tasks as it should, but for users that do have tasks there it looks like they are getting all the tasks in their gantt chart.
