### ISSUE TITLE
[lopri] Switch to integrated date fields

### ISSUE THREAD

**Issue by mattbell87** [DeBortoliWines/dotProject#30]
Currently date fields use a JavaScript pop-up. There are multiple issues with this method.

As stated by @cleary 
> the current datepicker opens in a separate window - this often gets lost behind other windows, or on large screens when it's not opening within the bounds of the parent window
it also doesn't fit the window dimensions properly on some browsers

A good solution would be to use html5 date fields and potentially use a fallback library for more obscure browsers.

**Comment by cleary** [comment]
Hi Matt, 
Thanks for this. In short, I'm more excited about implementing html5 date fields than another external js/jquery library - keen to see where you go with this. 

Thanks -

**Comment by mattbell87** [comment]
Gist for migrating dates

https://gist.github.com/mattbell87/37e1b5fec15f9339972dcac88282f902

**Comment by cleary** [comment]
Cool, I'm not sure what I'm looking at though :P

**Comment by mattbell87** [comment]
Oh sorry, that was mainly for my own reference. It's just a bit of html/js that migrates a single field.

**Comment by mattbell87** [comment]
I pushed some changes to [DeBortoliWines/30-modernise-date-pickers](/DeBortoliWines/dotProject/tree/30-modernise-date-pickers) for the task log dates.

The thing is I'm having a bit of trouble getting them to save. For some reason they're going back to the old values and I'm not seeing any errors (looked on-screen, js console and in the apache log file). I get that it could be something to do with the format, so I've added some changes to CDate to help with reading and outputting HTML5 formats. I've also combined the date/times in to datetime-local fields which could be part of the problem, I removed the code that previously combined them in to the hidden field.

Anyone got a spare few moments to help out or point me in the right direction? Cheers.

**Comment by cleary** [comment]
Hey Matt, 
@Givo29 had a bit of a look this week - his finding "the js datepicker wasn't posting any data" but that was as far as he got though I'm afraid (I got him onto a different project).

Hopefully that's of some assistance - have a great weekend :)

**Comment by cleary** [comment]
Hey @mattbell87 - thanks for organising the pull request for this, quick question - 

It looks like your branch has been based from dotproject/devel?

As a heads up (and I'm at fault for not having sorted this process out sooner, or communicating properly once sorted), the workflow I'd like to employ for these dbw initiated features is:

1. First and foremost, base from DeBortoliWines/master - our master is our production branch and is based off upstream dotproject/master, but with extra cherry-picked features/fixes. Essentially a next dot release candidate for upstream with in-house production testing. 
A lot of the features Adam is pulling into devel I see as potential for the next major release (3.x), but not necessarily tested well enough to go straight into production, so I want to keep control on our DeBortoliWines/master codebase as a production ready branch.

2. Once the feature is tested and confirmed functioning in our environment, create a PR for our DeBortoliWines/master branch

3. Then, create a new branch based off upstream dotporject/devel, merge your changes in and create an upstream PR. 

This will hopefully minimise the amount of work required merging the features into our production branch, which is your primary target - 

Let me know if none of that makes sense and I'll have another go at trying to explain :P

**Comment by cleary** [comment]
PS for this branch, I'll cherry-pick into our master, but I'd like to employ the process above for any future work -

Thanks!

**Comment by mattbell87** [comment]
Yes it was based on dotProject/devel. Thanks for that, I had actually been wondering recently about which branch is the best to base from. I'll stick with this workflow from now on.

**Comment by cleary** [comment]
Awesome, thanks!

**Comment by cleary** [comment]
hey @mattbell87, 
I've done a little testing to confirm functionality - it looks like the autocalculate buttons (duration, finish date) are broken when adding a new task - clicking them does nothing:

![Screenshot_20190812_145546](https://user-images.githubusercontent.com/2577966/62846171-461e5f00-bd11-11e9-81fe-9f30e07317b6.png)

**Comment by mattbell87** [comment]
Ah they hadn't been fixed for the new fields. I've patched, cherry picked and opened a new PR.
