### ISSUE TITLE
[lopri] Task logs sometimes filter by logged in user, should be All Users (all the time)

### ISSUE THREAD

**Issue by cleary** [DeBortoliWines/dotProject#36]
![Screenshot_20190709_112933](https://user-images.githubusercontent.com/2577966/60852851-d530e680-a23c-11e9-8803-891d94538dfb.png)

**Comment by mattbell87** [comment]
Hey @cleary from working on #8 I recall dotProject appears to remember what you had that option set to for the session (even if you navigate away). I noticed that after I set the default item to All Users. Is that what's happening?

**Comment by cleary** [comment]
Hi @mattbell87 thanks for the heads up - I think you're spot on, once set to All Users it will remember.
Logging into a fresh session is when it defaults to your username.

I thought I was going crazy, I'd seen it, other people had seen it, but I was having real trouble replicating it :P
