### ISSUE TITLE
[medpri] LDAP extended: ldap_template_role_for_copy_permissions_title System Setting is ignored

### ISSUE THREAD

**Issue by cleary** [DeBortoliWines/dotProject#38]
**Test:** Modify the default role title to another Role that exists

**Expected Outcome(s):**
 * Newly created roles should have all the same permissions of the role NOW defined as default

**Result:** Failed - New role was created from the ‘normal’ Role ID

**Comment by rafaelqg** [comment]
Issue fixed.
It was missing the inclusion of global variable "$dPconfig" in the addRoleToUser method, of the CLDAPExtended class.
