### ISSUE TITLE
[lopri] LDAP Extended: validate input for ldap_template_role_for_copy_permissions_title System Setting

### ISSUE THREAD

**Issue by cleary** [DeBortoliWines/dotProject#39]
**Test:** Modify the default role title to another Role that DOESN’T exist

**Expected Outcome:** The role name should be validated on submit, and throw an error if the role doesn’t exist
 * Actual Outcome: Role name was not validated and was saved

**Result:** Failed - use a dropdown(?), at least validate

**Comment by rafaelqg** [comment]
Fixed. The validation occurs before run the synchronization.
It was not possible to make the validation on dotProject configuration screen save or make a dynamic dropdown without change core files.
Change was include in the begining of run_syncronization.php file.

**Comment by cleary** [comment]
Adjust the error message so it's clearer that it's caused by the LDAP Extended module

**Comment by cleary** [comment]
Hi @rafaelqg, 
I rebuilt a fresh instance based on this LDAP extended branch, this error is coming up even if the module is not enabled:

![image](https://user-images.githubusercontent.com/2577966/67904342-2c7b0e00-fbc2-11e9-8414-77cbefdcb184.png)

![image](https://user-images.githubusercontent.com/2577966/67904371-44eb2880-fbc2-11e9-9c31-130afa6d42fc.png)

**Comment by rafaelqg** [comment]
Hi @cleary , I have just fixed that with the last commit. 
Now, before processing LDAP extended logic, it first verifies if module is active.
