### ISSUE TITLE
[hipri] Email interface to tasks for logs

### ISSUE THREAD

**Issue by cleary** [DeBortoliWines/dotProject#5]
Problem: A significant amount of time is spent duplicating email communications as task logs. 
For discussion: Use email to target individual tasks via email, and copy the core email attributes/content into a task log.

@mattbell87 - is this something that falls in your wheelhouse?
@ajdonnison - do you have thoughts on specific identifier/implementation paths for doing this?

**Comment by ajdonnison** [comment]
One way of doing this is to establish an IMAP or POP account that dotproject can monitor, and any emails that are replies to task emails or have a particular task id in the subject can fairly easily be pulled in as task logs.  This is probably the easiest to implement on both ends.

Other mechanisms I've seen, for instance in Eventum, use a pseudo-email address that includes the task id - that, however, tends to require more work setting up in the mail server that has to deliver them, although is less work in the target program.  IMHO getting people to do complicated setups at their mail server is going to be harder than just writing a mail client/parser.

**Comment by cleary** [comment]
This has changed priority, it's the primary focus feature for Planning now -

@Givo29 will be the primary developer resource with mentoring by @benletchford 
The brief offline discussion that we had aligns with @ajdonnison 's recommendation, so I that'll be the path we're most likely to take. 

We have 2 weeks to do a feasibility investigation, and will prepare a timeline for implementation after that point (if deemed feasible).

**Comment by cleary** [comment]
feasibility complete. Next steps tbd

**Comment by cleary** [comment]
Minimum Viable Product complete, deploying live today.

Key Details:
1. Only supports Gmail, using the Gmail API
1. Minimal documentation
1. All config is done in the run script for now, it's not implemented as a module
1. Rate limited - 5 emails per minute by default
1. Attachments and inline images are discarded

**Comment by cleary** [comment]
![Screenshot_20191203_120305](https://user-images.githubusercontent.com/2577966/70007570-df28fc80-15c4-11ea-911a-d12f2e87aa0d.png)
