### ISSUE TITLE
[lopri] Rich Text Editing for text input dialogs

### ISSUE THREAD

**Issue by cleary** [DeBortoliWines/dotProject#6]
The rationale for this one is just being able to handle/insert clickable hyperlinks/highlighting important details etc in walls of text (long/many task logs) etc - 

As far as I understand, there's plenty of JS implementations that would bolt on ok for the frontend component, I'm not sure what would be required in the backend db fields/etc 

@mattbell87 can you take a look at this one?
@ajdonnison any thoughts/recommendations/pitfalls we should be aware of?

**Comment by mattbell87** [comment]
Thoughts on QuillJS anyone? https://quilljs.com/

**Comment by careck** [comment]
I love QuillJS, it is a wonderful and minimalist editor.

Kind regards,

Carsten Eckelmann

*Carsten Eckelmann* { director }
M: 0458 795 544
E: carsten@2pisoftware.com
2pisoftware.com

**Comment by cleary** [comment]
Looks like a fantastic tool to me :)

**Comment by rafaelqg** [comment]
Looks great! How quills output its formatted content? It utilizes HTML for formatting? Or adopts some custom pattern?

**Comment by mattbell87** [comment]
I had a quick go at this issue. Check out the rich edit branch and look at the company description.

**Comment by mattbell87** [comment]
![richedit](https://user-images.githubusercontent.com/2722612/59143840-c0c9b600-8a12-11e9-9fbe-74dc82b58bed.gif)

**Comment by cleary** [comment]
Hey @mattbell87 - that looks great! Functionally spot on, content is displayed nicely after submit.

Any chance we can change the ratio of editing space vs toolbar space though? It doesn't immediately jump out as an edit area to my eyes due to the large area taken up by the toolbar - eg

![Screenshot_20190611_144946](https://user-images.githubusercontent.com/2577966/59244513-29ee3b00-8c58-11e9-8943-200521d23f6f.png)

**Comment by cleary** [comment]
@mattbell87 - just following up with a few people on this, if it speeds your path to getting it into our build, can you focus on task logs as the highest priority, followed by Project/Task descriptions -

Thanks -

**Comment by cleary** [comment]
@mattbell87 I've demo'd this to the team, and they are champing at the bit - is this something you are able to push in soon?

**Comment by Givo29** [comment]
Hi everyone,
I have added the rich text editor to adding new projects, adding new tasks and adding new tasks logs and made them display accordingly.

**Comment by mattbell87** [comment]
Hey @cleary yep I'll make those couple of changes. Also thanks @Givo29!
