### ISSUE TITLE
Task log tab: User list ordering and default View changes

### ISSUE THREAD

**Issue by cleary** [DeBortoliWines/dotProject#8]
Hi @mattbell87, 
Following on from the user list clean up that you did recently (thank you!), I've found another list that looks like it slipped through the net - 

If you open a task, then head into the Task Logs tab, you'll find an incorrectly ordered/filtered user list drop down in there -

Secondarily, the filter is set by default to just show the logged-in User's task logs, which is unexpected behaviour (because it's easy to assume there are no logs if you miss noticing that a filter has been applied). 

Can you please do two patch/pull requests to
1. update the sorting/ordering of the list
2. Show task logs from All Users by default

Thanks,

**Comment by mattbell87** [comment]
Hey @cleary as discussed I'll look at this one as priority. I've actually looked at it a few times, I just have to go and refresh myself on what I did with the last ones.

**Comment by cleary** [comment]
Thanks Matt!

**Comment by mattbell87** [comment]
Affected lines https://github.com/DeBortoliWines/dotProject/blob/264c64e91b00212712ad0ff075d14c99166a2feb/modules/projects/vw_logs.php#L34-L38
